hosting: implement a console host
sensate-iot/dsmr-parser pull request #2
Opened 2021-03-03 23:53 UTC by michelmegens

Implement a console host in order to improve the experience when running the DSMR parser service as a console application. The console host uses a manual cancellation event to allow the user to easily stop the application using <CTRL>+C.

2021-03-03 23:59 UTC, sensateiot-cicd requested changes
Nitpicking: add some newlines.

2021-03-03 23:59 UTC, sensateiot-cicd commented on SensateIoT.SmartEnergy.Dsmr.Parser.Service/Application/ConsoleHost.cs
> +using System.Threading;
Add new lines.

2021-03-04 00:00 UTC, michelmegens commented on SensateIoT.SmartEnergy.Dsmr.Parser.Service/Application/ConsoleHost.cs
> +using System.Threading;
Done!

2021-03-04 00:00 UTC, sensateiot-cicd approved these changes
Approved!

2021-03-04 00:02 UTC, merged